Chart/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name = "home"),
]

Chartjs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include("Chart.urls")),
    path('admin/', admin.site.urls),
]

Chart/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils.translation import ugettext_lazy as _

# Create your models here.
class UserType(models.Model):
	usertype = models.CharField(max_length = 30, unique = True)
	user_count = models.IntegerField(default = 0)

	class Meta:
		verbose_name = _('UserType')
		verbose_name_plural = _('UserTypes')

	def __str__(self):
		return self.usertype

class UserManager(BaseUserManager):
	def create_user(self, email, password = None):
		if not email:
			raise ValueError("Email is not given")
		user = self.model(
				email = self.normalize_email(email),
			)
		user.set_password(password)
		user.save(using = self._db)
		return user

	def create_superuser(self, email, password):
		user = self.create_user(
				email = self.normalize_email(email),
				password = password,
			)
		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.save(using = self._db)
		return user

class User(AbstractBaseUser):
	username = None
	email = models.EmailField(verbose_name = "Email", max_length = 100, unique = True )
	name = models.CharField(verbose_name = "Name", max_length = 50)
	mobile = models.BigIntegerField(unique= True, blank = True, null = True, editable =True)
	is_admin = models.BooleanField(default = False)
	is_staff = models.BooleanField(default = False)
	is_active = models.BooleanField(default = True)
	user_type = models.ForeignKey(UserType, on_delete = models.DO_NOTHING, blank = True, null = True)

	class Meta:
		verbose_name = _('User')
		verbose_name_plural = _('Users')

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []

	objects = UserManager()

	def __str__(self):
		return self.email

	def has_perm(self, perm, obj=None):
		return self.is_admin

	def has_module_perms(self, app_label):
		return True

Chart/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import UserType, User
from django.contrib import messages

# Create your views here.
def index(request):
	roles = UserType.objects.all()
	ides = UserType.objects.all().values_list('id', flat = True)
	cons = ides.count()
	for i in range(cons):
		usre = User.objects.filter(user_type = ides[i])
		countr = usre.count()
		role = UserType.objects.get(id = ides[i])
		role.user_count = 0
		role.user_count+=countr
		role.save()

	if request.method == 'POST':
		email = request.POST.get('email')
		name = request.POST.get('name')
		mobile = request.POST.get('mobile')
		password1 = request.POST.get('password1')
		password2 = request.POST.get('password2')
		user_type = request.POST.get('user_type')

		if password1 == password2:
			if User.objects.filter(email = email).exists():
				messages.info(request, "Email taken")
				return render(request, "base.html", {'roles': roles})
			else:
				user = User(email=email, name = name, mobile = mobile, user_type = UserType.objects.get(id = user_type))
				user.set_password(password1)
				user.save()
				ids = UserType.objects.all().values_list('id', flat = True)
				con = ids.count()
				for i in range(con):
					usr = User.objects.filter(user_type = ids[i])
					counter = usr.count()
					role = UserType.objects.get(id = ids[i])
					role.user_count = 0
					role.user_count+=counter
					role.save()
				return render(request, 'base.html', {'roles': roles})
		else:
			messages.info(request, "Password do not Match")
			return render(request, 'base.html', {'roles': roles})

	return render(request, 'base.html', {'roles': roles})
	

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <!--Chart js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>DATA VISUALIZATION</title>
    <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 45%;
      border-spacing: 0;
      border: 0; margin:0px;
    }
    tr:first-child td, tr:first-child th {
    border-top-left-radius: 8px; border-top-right-radius: 8px;
    }

    tr:last-child td {
    border-bottom-left-radius: 8px; border-bottom-right-radius: 8px;
    }

    td, th {
      /*border: 1px solid #dddddd;*/
      text-align: left;
      padding: 6px;
      border-bottom-width: 0px;
    }

    tr:nth-child(even) {
      background-color: white;
    }
    tr:nth-child(odd) {
      background-color: black;
    }
    div.container1 {
      width:1000px;
      margin: auto;
      border: 3px solid #000000;
    }
    </style>
  </head>
  <body style="background-image: url({% static 'img.jpg' %}); background-repeat: no-repeat; background-attachment: fixed; background-size: cover;">
    <script>
      $(document).ready(function(){
      var ctx = document.getElementById('myChart').getContext('2d');
      var myChart = new Chart(ctx, {
          type: 'pie',
          data: {
              labels: [{% for usr in roles %}'{{ usr.usertype }}',{% endfor %}],
              datasets: [{
                  label: '# of Votes',
                  data: [{% for usr in roles %}{{ usr.user_count }},{% endfor %}],
                  backgroundColor: [
                      'rgba(255, 99, 132, 0.2)',
                      'rgba(54, 162, 235, 0.2)',
                      'rgba(255, 206, 86, 0.2)',
                      'rgba(75, 192, 192, 0.2)',
                      'rgba(153, 102, 255, 0.2)',
                      'rgba(255, 159, 64, 0.2)'
                  ],
                  borderColor: [
                      'rgba(255, 99, 132, 1)',
                      'rgba(54, 162, 235, 1)',
                      'rgba(255, 206, 86, 1)',
                      'rgba(75, 192, 192, 1)',
                      'rgba(153, 102, 255, 1)',
                      'rgba(255, 159, 64, 1)'
                  ],
                  borderWidth: 2
              }]
          },
          options: {
              /*responsive: true,*/
              scales: {
                  yAxes: [{
                      ticks: {
                          beginAtZero: true
                      }
                  }]
              }
          }
      });
    });
    </script>
    <center>
   <div class="container">
    <form method="post">
      {% csrf_token %}
      <br>
        <table>
          <tr>
            <td style="color: white"><b>Name:</b></td>
            <td><input type="text" name="name" size="40"></td>
          </tr>
          <tr>
            <td><b>Email:</b></td>
            <td><input type="text" name="email" size="40"></td>
          </tr>
          <tr>
            <td style="color: white"><b>Password:</b></td>
            <td><input type="password" name="password1" size="40"></td>
          </tr>
          <tr>
            <td><b>Confirm Password:</b></td>
            <td><input type="password" name="password2" size="40"></td>
          </tr>
          <tr>
            <td style="color: white"><b>Mobile:</b></td>
            <td><input type="number" name="mobile" size="40"></td>
          </tr>
          <tr>
            <td><b>User Type:</b></td>
            <td><select name="user_type" id="id_user_type" style="width: 150px">
                {% for rol in roles %}
                  <option value="{{ rol.id }}">{{ rol.usertype }}</option>
                {% endfor %}
                </select></td>
          </tr>
        </table>
      <br>
      <input type="submit" value="Submit">
    </form>
    {% for msg in messages %}
      {{msg}}
    {% endfor %}
    <br>
    <div class="container1">
      <canvas id="myChart" width="400" height="100"></canvas></div>
    </div>
  </center>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>